### PR TITLE
Fix/eigen3.4.0

### PR DESCRIPTION
**Pull request by simonkerscher**
This makes signal_logger compile with Eigen 3.3.7 and 3.4.0

See also https://github.com/ANYbotics/signal_logger/issues/3

### CODE REVIEW

**Comment by hogabrie** [comment]
Thanks @simonkerscher for the commit. I would like to preserve your authorship, for that I would ask you to remove the jenkins pipeline from this MR, s.t. we can merge this without "dependency" on your tools.

**Comment by simonkerscher** [comment]
@hogabrie I have now based my changes of your master branch

**Comment by hogabrie** [comment]
Thank you, changes will be available shortly :)

**Comment by hogabrie** [comment]
Merged.

**Pull request closed without merging**
